### ISSUE TITLE
Cannot use import statement outside a module issue

### ISSUE THREAD

**Issue by codeBelt** [LuudJanssen/localforage-cache#1]
I am using [NextJS](https://nextjs.org/) and when I try to use this library I get the following issue:

`Cannot use import statement outside a module`

From what I've [read](https://github.com/vercel/next.js/issues/9890#issuecomment-569822580) is you library is not compatible with both Node.js and the Browser.

**Comment by LuudJanssen** [comment]
Hi @codeBelt! Sorry for the (very) late reply, was not actively maintaining this library.

This library is kind of acting like an ESModule but without being marked as one, which is a mistake from my part. I'm depricating this library, because I'm not in a position to actively maintain it, but you can probably solve this by using Next.js's built-in [module transpilation](https://nextjs.org/docs/advanced-features/compiler#module-transpilation) or copying the source file and moving it into your own repository.

Again, sorry for the mistake and the late reply!
